// Auto-generated by scripts/generate-search-index.js. Do not edit by hand.
import type { GlobalSearchItem } from './types'

export const SCANNED_PROJECT_SEARCH_ITEMS: GlobalSearchItem[] = [
  {
    "id": "feature:auth",
    "title": "Auth",
    "description": "Feature module components/features/auth",
    "type": "feature",
    "route": "/(auth)/login",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "auth",
      "auth"
    ],
    "alias": []
  },
  {
    "id": "feature:categories",
    "title": "Categories",
    "description": "Feature module components/features/categories",
    "type": "feature",
    "route": "/(app)/(tabs)/explore",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "categories",
      "categories"
    ],
    "alias": []
  },
  {
    "id": "feature:course-detail",
    "title": "Course Detail",
    "description": "Feature module components/features/course-detail",
    "type": "feature",
    "route": "/(app)/(tabs)/explore",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "course-detail",
      "course",
      "detail"
    ],
    "alias": []
  },
  {
    "id": "feature:course-preview",
    "title": "Course Preview",
    "description": "Feature module components/features/course-preview",
    "type": "feature",
    "route": "/(app)/(tabs)/explore",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "course-preview",
      "course",
      "preview"
    ],
    "alias": []
  },
  {
    "id": "feature:home",
    "title": "Home",
    "description": "Feature module components/features/home",
    "type": "feature",
    "route": "/(app)/(tabs)",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "home",
      "home"
    ],
    "alias": []
  },
  {
    "id": "feature:learning",
    "title": "Learning",
    "description": "Feature module components/features/learning",
    "type": "feature",
    "route": "/(app)/(tabs)/my-learn",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "learning",
      "learning"
    ],
    "alias": [
      "Learning",
      "Bài học"
    ]
  },
  {
    "id": "feature:lecturer",
    "title": "Lecturer",
    "description": "Feature module components/features/lecturer",
    "type": "feature",
    "route": "/(app)/(tabs)",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "lecturer",
      "lecturer"
    ],
    "alias": []
  },
  {
    "id": "feature:my-courses",
    "title": "My Courses",
    "description": "Feature module components/features/my-courses",
    "type": "feature",
    "route": "/(app)/(tabs)/explore",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "my-courses",
      "my",
      "courses"
    ],
    "alias": []
  },
  {
    "id": "feature:profile",
    "title": "Profile",
    "description": "Feature module components/features/profile",
    "type": "feature",
    "route": "/(app)/(tabs)/profile",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "profile",
      "profile"
    ],
    "alias": [
      "Profile",
      "Hồ sơ"
    ]
  },
  {
    "id": "feature:wallet",
    "title": "Wallet",
    "description": "Feature module components/features/wallet",
    "type": "feature",
    "route": "/(app)/wallet",
    "icon": "zap",
    "keywords": [
      "feature",
      "chức năng",
      "wallet",
      "wallet"
    ],
    "alias": [
      "Wallet",
      "Ví"
    ]
  },
  {
    "id": "navigation:/",
    "title": "Home",
    "description": "Navigation target found in components/features/course-detail/EmptyCourseView.tsx",
    "type": "route",
    "route": "/",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route"
    ],
    "alias": []
  },
  {
    "id": "navigation:/(app)",
    "title": "Home",
    "description": "Navigation target found in components/features/auth/CompleteProfileFeature.tsx",
    "type": "route",
    "route": "/(app)",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route"
    ],
    "alias": []
  },
  {
    "id": "navigation:/(app)/(tabs)",
    "title": "Home",
    "description": "Navigation target found in app/(app)/_layout.tsx",
    "type": "route",
    "route": "/(app)/(tabs)",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route"
    ],
    "alias": []
  },
  {
    "id": "navigation:/(app)/(tabs)/my-learn",
    "title": "My Learning",
    "description": "Navigation target found in app/(app)/(tabs)/notifications.tsx",
    "type": "tab",
    "route": "/(app)/(tabs)/my-learn",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "my-learn"
    ],
    "alias": [
      "My Learning",
      "Khóa học của tôi"
    ]
  },
  {
    "id": "navigation:/(app)/(tabs)/profile",
    "title": "Profile",
    "description": "Navigation target found in components/features/lecturer/LecturerFeature.tsx",
    "type": "tab",
    "route": "/(app)/(tabs)/profile",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "profile"
    ],
    "alias": [
      "Profile",
      "Hồ sơ"
    ]
  },
  {
    "id": "navigation:/(app)/complete-profile",
    "title": "Complete Profile",
    "description": "Navigation target found in app/(app)/_layout.tsx",
    "type": "profile",
    "route": "/(app)/complete-profile",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "complete-profile"
    ],
    "alias": [
      "Complete Profile",
      "Hoàn thiện hồ sơ"
    ]
  },
  {
    "id": "navigation:/(app)/course/${slug}",
    "title": "${slug}",
    "description": "Navigation target found in app/(app)/(tabs)/notifications.tsx",
    "type": "route",
    "route": "/(app)/course/${slug}",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "course",
      "${slug}"
    ],
    "alias": [
      "Course",
      "Khóa học",
      "${slug}"
    ]
  },
  {
    "id": "navigation:/(app)/explore",
    "title": "Explore",
    "description": "Navigation target found in app/(app)/(tabs)/my-learn.tsx",
    "type": "tab",
    "route": "/(app)/explore",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "explore"
    ],
    "alias": [
      "Explore",
      "Khám phá",
      "Search",
      "Tìm kiếm"
    ]
  },
  {
    "id": "navigation:/(app)/favorites",
    "title": "Favorites",
    "description": "Navigation target found in components/features/profile/components/ProfileActions.tsx",
    "type": "screen",
    "route": "/(app)/favorites",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "favorites"
    ],
    "alias": [
      "Favorites",
      "Yêu thích"
    ]
  },
  {
    "id": "navigation:/(app)/language",
    "title": "Language",
    "description": "Navigation target found in components/features/profile/components/ProfileActions.tsx",
    "type": "language",
    "route": "/(app)/language",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "language"
    ],
    "alias": [
      "Language",
      "Ngôn ngữ"
    ]
  },
  {
    "id": "navigation:/(app)/learning/${slug}",
    "title": "${slug}",
    "description": "Navigation target found in app/(app)/(tabs)/notifications.tsx",
    "type": "route",
    "route": "/(app)/learning/${slug}",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "learning",
      "${slug}"
    ],
    "alias": [
      "Learning",
      "Bài học",
      "${slug}"
    ]
  },
  {
    "id": "navigation:/(app)/profile",
    "title": "Profile",
    "description": "Navigation target found in src/utils/notifications.ts",
    "type": "tab",
    "route": "/(app)/profile",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "profile"
    ],
    "alias": [
      "Profile",
      "Hồ sơ"
    ]
  },
  {
    "id": "navigation:/(app)/wallet",
    "title": "Wallet",
    "description": "Navigation target found in app/payment-result.tsx",
    "type": "wallet",
    "route": "/(app)/wallet",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "wallet"
    ],
    "alias": [
      "Wallet",
      "Ví"
    ]
  },
  {
    "id": "navigation:/(auth)/login",
    "title": "Login",
    "description": "Navigation target found in components/features/auth/OnboardingFeature.tsx",
    "type": "route",
    "route": "/(auth)/login",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "login"
    ],
    "alias": [
      "Login",
      "Đăng nhập"
    ]
  },
  {
    "id": "navigation:/(auth)/onboarding",
    "title": "Onboarding",
    "description": "Navigation target found in app/(app)/_layout.tsx",
    "type": "route",
    "route": "/(auth)/onboarding",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "onboarding"
    ],
    "alias": [
      "Onboarding",
      "Giới thiệu"
    ]
  },
  {
    "id": "navigation:/(auth)/register",
    "title": "Register",
    "description": "Navigation target found in components/features/auth/PasswordFeature.tsx",
    "type": "route",
    "route": "/(auth)/register",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "register"
    ],
    "alias": [
      "Register",
      "Đăng ký"
    ]
  },
  {
    "id": "navigation:/(lecturer)/lecturer",
    "title": "Lecturer",
    "description": "Navigation target found in components/features/profile/components/ProfileActions.tsx",
    "type": "route",
    "route": "/(lecturer)/lecturer",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "lecturer"
    ],
    "alias": [
      "lecturer"
    ]
  },
  {
    "id": "navigation:/course/${course.slug}",
    "title": "${course.slug}",
    "description": "Navigation target found in components/features/home/CourseCard.tsx",
    "type": "route",
    "route": "/course/${course.slug}",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "course",
      "${course.slug}"
    ],
    "alias": [
      "Course",
      "Khóa học",
      "${course.slug}"
    ]
  },
  {
    "id": "navigation:/course/category/${category.slug}",
    "title": "${category.slug}",
    "description": "Navigation target found in components/features/categories/CategoriesContent.tsx",
    "type": "route",
    "route": "/course/category/${category.slug}",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "course",
      "category",
      "${category.slug}"
    ],
    "alias": [
      "Course",
      "Khóa học",
      "category",
      "${category.slug}"
    ]
  },
  {
    "id": "navigation:/course/preview/${courseId}",
    "title": "${courseId}",
    "description": "Navigation target found in app/(app)/course/[slug].tsx",
    "type": "route",
    "route": "/course/preview/${courseId}",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "course",
      "preview",
      "${courseId}"
    ],
    "alias": [
      "Course",
      "Khóa học",
      "preview",
      "${courseId}"
    ]
  },
  {
    "id": "navigation:/explore",
    "title": "Explore",
    "description": "Navigation target found in app/(app)/favorites/index.tsx",
    "type": "tab",
    "route": "/explore",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "explore"
    ],
    "alias": [
      "Explore",
      "Khám phá",
      "Search",
      "Tìm kiếm"
    ]
  },
  {
    "id": "navigation:/language",
    "title": "Language",
    "description": "Navigation target found in components/features/profile/SettingsFeature.tsx",
    "type": "language",
    "route": "/language",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "language"
    ],
    "alias": [
      "Language",
      "Ngôn ngữ"
    ]
  },
  {
    "id": "navigation:/learning/${course.slug}",
    "title": "${course.slug}",
    "description": "Navigation target found in app/(app)/(tabs)/my-learn.tsx",
    "type": "route",
    "route": "/learning/${course.slug}",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "learning",
      "${course.slug}"
    ],
    "alias": [
      "Learning",
      "Bài học",
      "${course.slug}"
    ]
  },
  {
    "id": "navigation:/login",
    "title": "Login",
    "description": "Navigation target found in components/features/course-detail/CourseDetailBottomBar.tsx",
    "type": "route",
    "route": "/login",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "login"
    ],
    "alias": [
      "Login",
      "Đăng nhập"
    ]
  },
  {
    "id": "navigation:/notifications",
    "title": "Notifications",
    "description": "Navigation target found in components/features/home/HomeHeader.tsx",
    "type": "tab",
    "route": "/notifications",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "notifications"
    ],
    "alias": [
      "Notifications",
      "Thông báo"
    ]
  },
  {
    "id": "navigation:/settings",
    "title": "Settings",
    "description": "Navigation target found in components/features/profile/components/ProfileActions.tsx",
    "type": "screen",
    "route": "/settings",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "settings"
    ],
    "alias": [
      "Settings",
      "Cài đặt"
    ]
  },
  {
    "id": "navigation:/wallet/transactions",
    "title": "Transactions",
    "description": "Navigation target found in app/(app)/wallet/index.tsx",
    "type": "transaction",
    "route": "/wallet/transactions",
    "icon": "navigation",
    "keywords": [
      "navigation",
      "menu",
      "route",
      "wallet",
      "transactions"
    ],
    "alias": [
      "Wallet",
      "Ví",
      "Transactions",
      "Giao dịch"
    ]
  },
  {
    "id": "route:/",
    "title": "Home",
    "description": "Project route /",
    "type": "screen",
    "route": "/",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình"
    ],
    "alias": []
  },
  {
    "id": "route:/(app)/(tabs)",
    "title": "Home",
    "description": "Project route /(app)/(tabs)",
    "type": "screen",
    "route": "/(app)/(tabs)",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình"
    ],
    "alias": []
  },
  {
    "id": "route:/(app)/(tabs)/explore",
    "title": "Explore",
    "description": "Project route /(app)/(tabs)/explore",
    "type": "tab",
    "route": "/(app)/(tabs)/explore",
    "icon": "grid",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "explore"
    ],
    "alias": [
      "Explore",
      "Khám phá",
      "Search",
      "Tìm kiếm"
    ]
  },
  {
    "id": "route:/(app)/(tabs)/my-learn",
    "title": "My Learning",
    "description": "Project route /(app)/(tabs)/my-learn",
    "type": "tab",
    "route": "/(app)/(tabs)/my-learn",
    "icon": "grid",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "my-learn"
    ],
    "alias": [
      "My Learning",
      "Khóa học của tôi"
    ]
  },
  {
    "id": "route:/(app)/(tabs)/notifications",
    "title": "Notifications",
    "description": "Project route /(app)/(tabs)/notifications",
    "type": "tab",
    "route": "/(app)/(tabs)/notifications",
    "icon": "grid",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "notifications"
    ],
    "alias": [
      "Notifications",
      "Thông báo"
    ]
  },
  {
    "id": "route:/(app)/(tabs)/profile",
    "title": "Profile",
    "description": "Project route /(app)/(tabs)/profile",
    "type": "tab",
    "route": "/(app)/(tabs)/profile",
    "icon": "grid",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "profile"
    ],
    "alias": [
      "Profile",
      "Hồ sơ"
    ]
  },
  {
    "id": "route:/(app)/(tabs)/settings",
    "title": "Settings",
    "description": "Project route /(app)/(tabs)/settings",
    "type": "screen",
    "route": "/(app)/(tabs)/settings",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "settings"
    ],
    "alias": [
      "Settings",
      "Cài đặt"
    ]
  },
  {
    "id": "route:/(app)/complete-profile",
    "title": "Complete Profile",
    "description": "Project route /(app)/complete-profile",
    "type": "profile",
    "route": "/(app)/complete-profile",
    "icon": "user",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "complete-profile"
    ],
    "alias": [
      "Complete Profile",
      "Hoàn thiện hồ sơ"
    ]
  },
  {
    "id": "route:/(app)/course/[slug]",
    "title": "Slug",
    "description": "Project route /(app)/course/[slug]",
    "type": "course",
    "route": "/(app)/course/[slug]",
    "icon": "book",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "course",
      "slug"
    ],
    "alias": [
      "Course",
      "Khóa học",
      "slug"
    ]
  },
  {
    "id": "route:/(app)/course/preview/[courseId]",
    "title": "CourseId",
    "description": "Project route /(app)/course/preview/[courseId]",
    "type": "course",
    "route": "/(app)/course/preview/[courseId]",
    "icon": "book",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "course",
      "preview",
      "courseId"
    ],
    "alias": [
      "Course",
      "Khóa học",
      "preview",
      "courseId"
    ]
  },
  {
    "id": "route:/(app)/favorites",
    "title": "Favorites",
    "description": "Project route /(app)/favorites",
    "type": "screen",
    "route": "/(app)/favorites",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "favorites"
    ],
    "alias": [
      "Favorites",
      "Yêu thích"
    ]
  },
  {
    "id": "route:/(app)/language",
    "title": "Language",
    "description": "Project route /(app)/language",
    "type": "language",
    "route": "/(app)/language",
    "icon": "globe",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "language"
    ],
    "alias": [
      "Language",
      "Ngôn ngữ"
    ]
  },
  {
    "id": "route:/(app)/learning/[slug]",
    "title": "Slug",
    "description": "Project route /(app)/learning/[slug]",
    "type": "lesson",
    "route": "/(app)/learning/[slug]",
    "icon": "play-circle",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "learning",
      "slug"
    ],
    "alias": [
      "Learning",
      "Bài học",
      "slug"
    ]
  },
  {
    "id": "route:/(app)/wallet",
    "title": "Wallet",
    "description": "Project route /(app)/wallet",
    "type": "wallet",
    "route": "/(app)/wallet",
    "icon": "credit-card",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "wallet"
    ],
    "alias": [
      "Wallet",
      "Ví"
    ]
  },
  {
    "id": "route:/(app)/wallet/transactions",
    "title": "Transactions",
    "description": "Project route /(app)/wallet/transactions",
    "type": "transaction",
    "route": "/(app)/wallet/transactions",
    "icon": "repeat",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "wallet",
      "transactions"
    ],
    "alias": [
      "Wallet",
      "Ví",
      "Transactions",
      "Giao dịch"
    ]
  },
  {
    "id": "route:/(auth)/login",
    "title": "Login",
    "description": "Project route /(auth)/login",
    "type": "route",
    "route": "/(auth)/login",
    "icon": "navigation",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "login"
    ],
    "alias": [
      "Login",
      "Đăng nhập"
    ]
  },
  {
    "id": "route:/(auth)/onboarding",
    "title": "Onboarding",
    "description": "Project route /(auth)/onboarding",
    "type": "route",
    "route": "/(auth)/onboarding",
    "icon": "navigation",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "onboarding"
    ],
    "alias": [
      "Onboarding",
      "Giới thiệu"
    ]
  },
  {
    "id": "route:/(auth)/phone",
    "title": "Phone Login",
    "description": "Project route /(auth)/phone",
    "type": "route",
    "route": "/(auth)/phone",
    "icon": "navigation",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "phone"
    ],
    "alias": [
      "Phone Login",
      "Đăng nhập điện thoại"
    ]
  },
  {
    "id": "route:/(auth)/register",
    "title": "Register",
    "description": "Project route /(auth)/register",
    "type": "route",
    "route": "/(auth)/register",
    "icon": "navigation",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "register"
    ],
    "alias": [
      "Register",
      "Đăng ký"
    ]
  },
  {
    "id": "route:/(auth)/verify-otp",
    "title": "Verify OTP",
    "description": "Project route /(auth)/verify-otp",
    "type": "route",
    "route": "/(auth)/verify-otp",
    "icon": "navigation",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "verify-otp"
    ],
    "alias": [
      "Verify OTP",
      "Xác thực OTP"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer",
    "title": "Lecturer",
    "description": "Project route /(lecturer)/lecturer",
    "type": "screen",
    "route": "/(lecturer)/lecturer",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer"
    ],
    "alias": [
      "lecturer"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/chapters",
    "title": "Chapters",
    "description": "Project route /(lecturer)/lecturer/chapters",
    "type": "screen",
    "route": "/(lecturer)/lecturer/chapters",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "chapters"
    ],
    "alias": [
      "lecturer",
      "chapters"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/courses",
    "title": "Courses",
    "description": "Project route /(lecturer)/lecturer/courses",
    "type": "screen",
    "route": "/(lecturer)/lecturer/courses",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "courses"
    ],
    "alias": [
      "lecturer",
      "courses"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/courses/[id]/edit",
    "title": "Edit",
    "description": "Project route /(lecturer)/lecturer/courses/[id]/edit",
    "type": "screen",
    "route": "/(lecturer)/lecturer/courses/[id]/edit",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "courses",
      "id",
      "edit"
    ],
    "alias": [
      "lecturer",
      "courses",
      "id",
      "edit"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/courses/[id]/stats",
    "title": "Stats",
    "description": "Project route /(lecturer)/lecturer/courses/[id]/stats",
    "type": "screen",
    "route": "/(lecturer)/lecturer/courses/[id]/stats",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "courses",
      "id",
      "stats"
    ],
    "alias": [
      "lecturer",
      "courses",
      "id",
      "stats"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/courses/[id]/users",
    "title": "Users",
    "description": "Project route /(lecturer)/lecturer/courses/[id]/users",
    "type": "screen",
    "route": "/(lecturer)/lecturer/courses/[id]/users",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "courses",
      "id",
      "users"
    ],
    "alias": [
      "lecturer",
      "courses",
      "id",
      "users"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/courses/[id]/users/detail",
    "title": "Detail",
    "description": "Project route /(lecturer)/lecturer/courses/[id]/users/detail",
    "type": "screen",
    "route": "/(lecturer)/lecturer/courses/[id]/users/detail",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "courses",
      "id",
      "users",
      "detail"
    ],
    "alias": [
      "lecturer",
      "courses",
      "id",
      "users",
      "detail"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/courses/create",
    "title": "Create",
    "description": "Project route /(lecturer)/lecturer/courses/create",
    "type": "screen",
    "route": "/(lecturer)/lecturer/courses/create",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "courses",
      "create"
    ],
    "alias": [
      "lecturer",
      "courses",
      "create"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/dashboard",
    "title": "Dashboard",
    "description": "Project route /(lecturer)/lecturer/dashboard",
    "type": "screen",
    "route": "/(lecturer)/lecturer/dashboard",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "dashboard"
    ],
    "alias": [
      "lecturer",
      "dashboard"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/discounts",
    "title": "Discounts",
    "description": "Project route /(lecturer)/lecturer/discounts",
    "type": "screen",
    "route": "/(lecturer)/lecturer/discounts",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "discounts"
    ],
    "alias": [
      "lecturer",
      "discounts"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/discounts/[id]/edit",
    "title": "Edit",
    "description": "Project route /(lecturer)/lecturer/discounts/[id]/edit",
    "type": "screen",
    "route": "/(lecturer)/lecturer/discounts/[id]/edit",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "discounts",
      "id",
      "edit"
    ],
    "alias": [
      "lecturer",
      "discounts",
      "id",
      "edit"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/discounts/create",
    "title": "Create",
    "description": "Project route /(lecturer)/lecturer/discounts/create",
    "type": "screen",
    "route": "/(lecturer)/lecturer/discounts/create",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "discounts",
      "create"
    ],
    "alias": [
      "lecturer",
      "discounts",
      "create"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/hold",
    "title": "Hold",
    "description": "Project route /(lecturer)/lecturer/hold",
    "type": "screen",
    "route": "/(lecturer)/lecturer/hold",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "hold"
    ],
    "alias": [
      "lecturer",
      "hold"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/lessons/[id]/edit",
    "title": "Edit",
    "description": "Project route /(lecturer)/lecturer/lessons/[id]/edit",
    "type": "screen",
    "route": "/(lecturer)/lecturer/lessons/[id]/edit",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "lessons",
      "id",
      "edit"
    ],
    "alias": [
      "lecturer",
      "lessons",
      "id",
      "edit"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/lessons/[id]/resources",
    "title": "Resources",
    "description": "Project route /(lecturer)/lecturer/lessons/[id]/resources",
    "type": "screen",
    "route": "/(lecturer)/lecturer/lessons/[id]/resources",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "lessons",
      "id",
      "resources"
    ],
    "alias": [
      "lecturer",
      "lessons",
      "id",
      "resources"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/lessons/create",
    "title": "Create",
    "description": "Project route /(lecturer)/lecturer/lessons/create",
    "type": "screen",
    "route": "/(lecturer)/lecturer/lessons/create",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "lessons",
      "create"
    ],
    "alias": [
      "lecturer",
      "lessons",
      "create"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/notifications",
    "title": "Notifications",
    "description": "Project route /(lecturer)/lecturer/notifications",
    "type": "tab",
    "route": "/(lecturer)/lecturer/notifications",
    "icon": "grid",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "notifications"
    ],
    "alias": [
      "lecturer",
      "Notifications",
      "Thông báo"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/payouts",
    "title": "Payouts",
    "description": "Project route /(lecturer)/lecturer/payouts",
    "type": "screen",
    "route": "/(lecturer)/lecturer/payouts",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "payouts"
    ],
    "alias": [
      "lecturer",
      "payouts"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/profile",
    "title": "Profile",
    "description": "Project route /(lecturer)/lecturer/profile",
    "type": "tab",
    "route": "/(lecturer)/lecturer/profile",
    "icon": "grid",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "profile"
    ],
    "alias": [
      "lecturer",
      "Profile",
      "Hồ sơ"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/quizzes-lesson",
    "title": "Quizzes Lesson",
    "description": "Project route /(lecturer)/lecturer/quizzes-lesson",
    "type": "screen",
    "route": "/(lecturer)/lecturer/quizzes-lesson",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "quizzes-lesson"
    ],
    "alias": [
      "lecturer",
      "quizzes-lesson"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/refund",
    "title": "Refund",
    "description": "Project route /(lecturer)/lecturer/refund",
    "type": "screen",
    "route": "/(lecturer)/lecturer/refund",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "refund"
    ],
    "alias": [
      "lecturer",
      "refund"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/refunds/[id]",
    "title": "Id",
    "description": "Project route /(lecturer)/lecturer/refunds/[id]",
    "type": "screen",
    "route": "/(lecturer)/lecturer/refunds/[id]",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "refunds",
      "id"
    ],
    "alias": [
      "lecturer",
      "refunds",
      "id"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/resources",
    "title": "Resources",
    "description": "Project route /(lecturer)/lecturer/resources",
    "type": "screen",
    "route": "/(lecturer)/lecturer/resources",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "resources"
    ],
    "alias": [
      "lecturer",
      "resources"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/wallets",
    "title": "Wallets",
    "description": "Project route /(lecturer)/lecturer/wallets",
    "type": "screen",
    "route": "/(lecturer)/lecturer/wallets",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "wallets"
    ],
    "alias": [
      "lecturer",
      "wallets"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/wallets/transactions/[id]",
    "title": "Id",
    "description": "Project route /(lecturer)/lecturer/wallets/transactions/[id]",
    "type": "screen",
    "route": "/(lecturer)/lecturer/wallets/transactions/[id]",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "wallets",
      "transactions",
      "id"
    ],
    "alias": [
      "lecturer",
      "wallets",
      "Transactions",
      "Giao dịch",
      "id"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/withdraw",
    "title": "Withdraw",
    "description": "Project route /(lecturer)/lecturer/withdraw",
    "type": "screen",
    "route": "/(lecturer)/lecturer/withdraw",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "withdraw"
    ],
    "alias": [
      "lecturer",
      "withdraw"
    ]
  },
  {
    "id": "route:/(lecturer)/lecturer/withdraw/create",
    "title": "Create",
    "description": "Project route /(lecturer)/lecturer/withdraw/create",
    "type": "screen",
    "route": "/(lecturer)/lecturer/withdraw/create",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "lecturer",
      "withdraw",
      "create"
    ],
    "alias": [
      "lecturer",
      "withdraw",
      "create"
    ]
  },
  {
    "id": "route:/(lecturer)/welcome",
    "title": "Welcome",
    "description": "Project route /(lecturer)/welcome",
    "type": "screen",
    "route": "/(lecturer)/welcome",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "welcome"
    ],
    "alias": [
      "welcome"
    ]
  },
  {
    "id": "route:/demo",
    "title": "Demo",
    "description": "Project route /demo",
    "type": "screen",
    "route": "/demo",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "demo"
    ],
    "alias": [
      "Demo"
    ]
  },
  {
    "id": "route:/payment-result",
    "title": "Payment Result",
    "description": "Project route /payment-result",
    "type": "screen",
    "route": "/payment-result",
    "icon": "smartphone",
    "keywords": [
      "route",
      "screen",
      "màn hình",
      "payment-result"
    ],
    "alias": [
      "Payment Result",
      "Kết quả thanh toán"
    ]
  }
]
